-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.boats
(
    boat_id serial NOT NULL,
    boat_name character varying(50) NOT NULL,
    boat_type boat_type NOT NULL,
    PRIMARY KEY (boat_id)
);

CREATE TABLE IF NOT EXISTS public.athletes
(
    athlete_id serial NOT NULL,
    athlete_name character varying(200) NOT NULL,
    graduation_year integer NOT NULL,
    is_rower boolean NOT NULL,
    primary_side side NOT NULL,
    swaps_sides boolean NOT NULL DEFAULT FALSE,
    PRIMARY KEY (athlete_id)
);

CREATE TABLE IF NOT EXISTS public.lineups
(
    lineup_id serial NOT NULL,
    boat_id integer NOT NULL,
    lineup_name character varying(100),
    PRIMARY KEY (lineup_id)
);

CREATE TABLE IF NOT EXISTS public.seat_assignments
(
    lineup_id integer NOT NULL,
    athlete_id integer NOT NULL,
    seat seat NOT NULL,
    PRIMARY KEY (lineup_id, athlete_id)
);

ALTER TABLE IF EXISTS public.lineups
    ADD FOREIGN KEY (boat_id)
    REFERENCES public.boats (boat_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.seat_assignments
    ADD FOREIGN KEY (lineup_id)
    REFERENCES public.lineups (lineup_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.seat_assignments
    ADD FOREIGN KEY (athlete_id)
    REFERENCES public.athletes (athlete_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;

END;